Repository flutter-form-builder-ecosystem/flutter_form_builder, pull requests merged in 2022-06, with the labels that each got.

#1031 Add a custom filter chip option to accept avatar
  packages/flutter_form_builder/lib/flutter_form_builder.dart
  packages/flutter_form_builder/lib/src/fields/form_builder_filter_chips.dart
  packages/flutter_form_builder/lib/src/options/form_builder_chip_option.dart
  packages/flutter_form_builder/test/form_builder_filter_chips_test.dart
Labels: package:core

#1041 WIP: docs: Add contributing files
  packages/form_builder_phone_field/example/CODE_OF_CONDUCT.md
  packages/form_builder_phone_field/example/CONTRIBUTING.md
Labels: documentation

#1051 WIP: ci(phone_field): Add build and deploy pipeline
  .github/workflows/form_builder_phone_field.yaml
  packages/form_builder_phone_field/example/android/app/build.gradle
  packages/form_builder_phone_field/example/android/build.gradle
  packages/form_builder_phone_field/example/android/gradle.properties
  packages/form_builder_phone_field/example/android/gradle/wrapper/gradle-wrapper.properties
  tools/pub_login.sh
Labels: enhancement

#1060 FormBuilderPhoneField Fix deploy pipeline
  .github/workflows/form_builder_phone_field.yaml
  tools/pub_login.sh
Labels: enhancement, package:phone_field

#1059 fix #1019
  packages/flutter_form_builder/lib/src/fields/form_builder_text_field.dart
  packages/flutter_form_builder/test/form_builder_text_field_test.dart
Labels: bug
